# Generated by Django 4.0.8 on 2022-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_data', models.DateField()),
                ('completed', models.BooleanField()),
                ('favorite', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
                ('kilometers', models.IntegerField()),
                ('meters', models.IntegerField()),
                ('miles', models.IntegerField()),
                ('feet', models.IntegerField()),
            ],
        ),
    ]
