# Generated by Django 4.0.8 on 2022-12-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0002_alter_nasa_feet_alter_nasa_kilometers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasa',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='nasa',
            name='favorite',
        ),
    ]
